"""using fw/os version + h_cpe

Revision ID: 414876b33bc4
Revises: 7a9bdb865589
Create Date: 2025-09-17 21:39:18.410655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414876b33bc4'
down_revision: Union[str, Sequence[str], None] = '7a9bdb865589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('h_cpe', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'h_cpe')
    # ### end Alembic commands ###
