"""using fw/os version

Revision ID: 7a9bdb865589
Revises: c6329f72e465
Create Date: 2025-09-06 16:53:35.755588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9bdb865589'
down_revision: Union[str, Sequence[str], None] = 'c6329f72e465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('os_family', sa.String(), nullable=False))
    op.alter_column('assets', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('assets', 'os_family')
    # ### end Alembic commands ###
