"""adding cascade deletes two

Revision ID: e5c457fc62f5
Revises: 4c38cea7ff46
Create Date: 2025-10-05 14:11:47.679604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c457fc62f5'
down_revision: Union[str, Sequence[str], None] = '4c38cea7ff46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('asset_cve_relations_cve_id_fkey'), 'asset_cve_relations', type_='foreignkey')
    op.drop_constraint(op.f('asset_cve_relations_asset_id_fkey'), 'asset_cve_relations', type_='foreignkey')
    op.create_foreign_key(None, 'asset_cve_relations', 'cves', ['cve_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'asset_cve_relations', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('capec_attack_relations_capec_id_fkey'), 'capec_attack_relations', type_='foreignkey')
    op.drop_constraint(op.f('capec_attack_relations_attack_id_fkey'), 'capec_attack_relations', type_='foreignkey')
    op.create_foreign_key(None, 'capec_attack_relations', 'attacks', ['attack_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'capec_attack_relations', 'capecs', ['capec_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cve_cwe_relations_cve_id_fkey'), 'cve_cwe_relations', type_='foreignkey')
    op.drop_constraint(op.f('cve_cwe_relations_cwe_id_fkey'), 'cve_cwe_relations', type_='foreignkey')
    op.create_foreign_key(None, 'cve_cwe_relations', 'cwes', ['cwe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cve_cwe_relations', 'cves', ['cve_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cwe_capec_relations_capec_id_fkey'), 'cwe_capec_relations', type_='foreignkey')
    op.drop_constraint(op.f('cwe_capec_relations_cwe_id_fkey'), 'cwe_capec_relations', type_='foreignkey')
    op.create_foreign_key(None, 'cwe_capec_relations', 'cwes', ['cwe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cwe_capec_relations', 'capecs', ['capec_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cwe_capec_relations', type_='foreignkey')
    op.drop_constraint(None, 'cwe_capec_relations', type_='foreignkey')
    op.create_foreign_key(op.f('cwe_capec_relations_cwe_id_fkey'), 'cwe_capec_relations', 'cwes', ['cwe_id'], ['id'])
    op.create_foreign_key(op.f('cwe_capec_relations_capec_id_fkey'), 'cwe_capec_relations', 'capecs', ['capec_id'], ['id'])
    op.drop_constraint(None, 'cve_cwe_relations', type_='foreignkey')
    op.drop_constraint(None, 'cve_cwe_relations', type_='foreignkey')
    op.create_foreign_key(op.f('cve_cwe_relations_cwe_id_fkey'), 'cve_cwe_relations', 'cwes', ['cwe_id'], ['id'])
    op.create_foreign_key(op.f('cve_cwe_relations_cve_id_fkey'), 'cve_cwe_relations', 'cves', ['cve_id'], ['id'])
    op.drop_constraint(None, 'capec_attack_relations', type_='foreignkey')
    op.drop_constraint(None, 'capec_attack_relations', type_='foreignkey')
    op.create_foreign_key(op.f('capec_attack_relations_attack_id_fkey'), 'capec_attack_relations', 'attacks', ['attack_id'], ['id'])
    op.create_foreign_key(op.f('capec_attack_relations_capec_id_fkey'), 'capec_attack_relations', 'capecs', ['capec_id'], ['id'])
    op.drop_constraint(None, 'asset_cve_relations', type_='foreignkey')
    op.drop_constraint(None, 'asset_cve_relations', type_='foreignkey')
    op.create_foreign_key(op.f('asset_cve_relations_asset_id_fkey'), 'asset_cve_relations', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(op.f('asset_cve_relations_cve_id_fkey'), 'asset_cve_relations', 'cves', ['cve_id'], ['id'])
    # ### end Alembic commands ###
